export const options = [
  { value: 'Addendum', label: 'Addendum' },
  { value: 'An Analysis', label: 'An Analysis' },
  { value: 'An Appraisal', label: 'An Appraisal' },
  { value: 'Article', label: 'Article' },
  { value: 'Banner', label: 'Banner' },
  { value: 'Biography', label: 'Biography' },
  { value: 'Birth Notice', label: 'Birth Notice' },
  { value: 'Blog', label: 'Blog' },
  { value: 'Brief', label: 'Brief' },
  { value: 'Caption', label: 'Caption' },
  { value: 'Chronology', label: 'Chronology' },
  { value: 'Column', label: 'Column' },
  { value: 'Correction', label: 'Correction' },
  { value: 'Economic Analysis', label: 'Economic Analysis' },
  { value: 'Editorial', label: 'Editorial' },
  { value: 'Editorial Cartoon', label: 'Editorial Cartoon' },
  { value: 'Editors Note', label: 'Editors Note' },
  { value: 'First Chapter', label: 'First Chapter' },
  { value: 'Front Page', label: 'Front Page' },
  { value: 'Glossary', label: 'Glossary' },
  { value: 'Interactive Feature', label: 'Interactive Feature' },
  { value: 'Interactive Graphic', label: 'Interactive Graphic' },
  { value: 'Interview', label: 'Interview' },
  { value: 'Letter', label: 'Letter' },
  { value: 'List', label: 'List' },
  { value: 'Marriage Announcement', label: 'Marriage Announcement' },
  { value: 'Military Analysis', label: 'Military Analysis' },
  { value: 'News', label: 'News' },
  { value: 'News Analysis', label: 'News Analysis' },
  { value: 'Newsletter', label: 'Newsletter' },
  { value: 'Obituary', label: 'Obituary' },
  { value: 'Obituary (Obit)', label: 'Obituary (Obit)' },
  { value: 'Op-Ed', label: 'Op-Ed' },
  { value: 'Paid Death Notice', label: 'Paid Death Notice' },
  { value: 'Postscript', label: 'Postscript' },
  { value: 'Premium', label: 'Premium' },
  { value: 'Question', label: 'Question' },
  { value: 'Quote', label: 'Quote' },
  { value: 'Recipe', label: 'Recipe' },
  { value: 'Review', label: 'Review' },
  { value: 'Schedule', label: 'Schedule' },
  { value: 'SectionFront', label: 'SectionFront' },
  { value: 'Series', label: 'Series' },
  { value: 'Slideshow', label: 'Slideshow' },
  { value: 'Special Report', label: 'Special Report' },
  { value: 'Statistics', label: 'Statistics' },
  { value: 'Summary', label: 'Summary' },
  { value: 'Text', label: 'Text' },
  { value: 'Video', label: 'Video' },
  { value: 'Web Log', label: 'Web Log' }
]
